export type IconSize = 'small' | 'medium' | 'large'
export type IconProps = {
	width: number
	height: number
	className?: string
}
export type IconName =
	| 'ri-arrow-right-s-line'
	| 'ri-arrow-up-s-line'
	| 'ri-arrow-left-s-line'
	| 'ri-arrow-down-s-line'
	| 'ri-check-fill'
	| 'ri-check-line'
	| 'ri-checkbox-blank-circle-fill'
	| 'ri-checkbox-blank-circle-line'
	| 'ri-checkbox-blank-fill'
	| 'ri-checkbox-blank-line'
	| 'ri-checkbox-circle-fill'
	| 'ri-checkbox-circle-line'
	| 'ri-checkbox-fill'
	| 'ri-checkbox-indeterminate-fill'
	| 'ri-checkbox-indeterminate-line'
	| 'ri-checkbox-line'
	| 'ri-close-circle-fill'
	| 'ri-close-circle-line'
	| 'ri-close-line'
	| 'ri-attachment-2'
	| 'ri-attachment-fill'
	| 'ri-attachment-line'
	| 'ri-message-fill'
	| 'ri-message-line'
	| 'ri-error-warning-fill'
	| 'ri-error-warning-line'
	| 'ri-alert-fill'
	| 'ri-alert-line'
	| 'ri-alarm-warning-fill'
	| 'ri-alarm-warning-line'
