import { IconName } from './types'
export const iconList: IconName[] = [
	'ri-arrow-right-s-line',
	'ri-arrow-up-s-line',
	'ri-arrow-left-s-line',
	'ri-arrow-down-s-line',
	'ri-check-fill',
	'ri-check-line',
	'ri-checkbox-blank-circle-fill',
	'ri-checkbox-blank-circle-line',
	'ri-checkbox-blank-fill',
	'ri-checkbox-blank-line',
	'ri-checkbox-circle-fill',
	'ri-checkbox-circle-line',
	'ri-checkbox-fill',
	'ri-checkbox-indeterminate-fill',
	'ri-checkbox-indeterminate-line',
	'ri-checkbox-line',
	'ri-close-circle-fill',
	'ri-close-circle-line',
	'ri-close-line',
]
